version: "3"
services:
  api:
    container_name: app
    build:
      context: .
    volumes:
      - .:/src/app
      # - /src/app/node_modules
    environment:
      NODE_ENV: development
      DEBUG: nodejs-docker-express:*
    ports:
      - "3000:3000"
    command: ["sh", "-c", "ts-node src/db/init.db.ts && ts-node src/scripts/insertData.scripts.ts && npm start"]

